package holo.sojourn.world.base.genlayers;

import net.minecraft.world.gen.layer.GenLayer;
import net.minecraft.world.gen.layer.IntCache;

public class GenLayerBase extends GenLayer
{
    int biomeID;
    
    public GenLayerBase(long par1, int biome)
    {
        super(par1);
        biomeID = biome;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int par1, int par2, int par3, int par4)
    {
        int[] aint = IntCache.getIntCache(par3 * par4);

        for (int i1 = 0; i1 < par4; ++i1)
        {
            for (int j1 = 0; j1 < par3; ++j1)
            {
                this.initChunkSeed((long)(par1 + j1), (long)(par2 + i1));
                aint[j1 + i1 * par3] = biomeID;
            }
        }

//        if (par1 > -par3 && par1 <= 0 && par2 > -par4 && par2 <= 0)
//        {
//            aint[-par1 + -par2 * par3] = 1;
//        }

        return aint;
    }
}